server:
  port: 8080

spring:
  datasource:
    url: ${mysql_url}
    username: ${mysql_username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update